### ISSUE TITLE
Can we download your fine-tuned FABE model?

### ISSUE THREAD

**Issue by WencongY** [lyr17/Frontdoor-Adjustment-Backdoor-Elimination#1]
Hello,

I have obtained access to the llama-2 models from Meta, but we do not have enough GPU resources to do the fine-tuning. Can you please share your fine-tuned llama-2-7b model weights with us? 

![Screenshot 2024-07-18 at 7 06 42 PM](https://github.com/user-attachments/assets/17d2e11a-5336-491a-9daf-1af09dfc5deb)

Thanks,
Wencong

**Comment by xuxiaoang** [comment]
> Hello,
> 
> I have obtained access to the llama-2 models from Meta, but we do not have enough GPU resources to do the fine-tuning. Can you please share your fine-tuned llama-2-7b model weights with us?
> 
> ![Screenshot 2024-07-18 at 7 06 42 PM](https://private-user-images.githubusercontent.com/58152496/350200104-17d2e11a-5336-491a-9daf-1af09dfc5deb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NDk4MzMsIm5iZiI6MTcyMTQ0OTUzMywicGF0aCI6Ii81ODE1MjQ5Ni8zNTAyMDAxMDQtMTdkMmUxMWEtNTMzNi00OTFhLTlkYWYtMWFmMDlkZmM1ZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA0MjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OWEyNjAxZGYwYjY5NTJjOTk3NDM2ZjQ2NzQyMDQxOGVlOTkzNzg1Njk4OTUxNWYwMDIzNzFkZDRhYjE5MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4LSSW8N2lNWPaijsYADdrSwUonM7rwTZVIc3BfSlG14)
> 
> Thanks, Wencong

Hello, thank you for your attention to our work!
We have uploaded our fine-tuned FABE model at Hugging Face and updated the README file, you can download fine-tuned FABE model at the following link:
https://huggingface.co/xxang/FABE
Thank you.

**Comment by WencongY** [comment]
Thank you so much. 

Closing the comment now.
